### ISSUE TITLE
CRS version 0.5 – Feedback 

### ISSUE THREAD

**Issue by LukaDPavic** [JoTec2002/TINF21C_AAS_Management#13]
Dear Customer (@mrentsch65),

we are currently in the process of finalizing the CRS and would like to know your opinion on the following use cases and requirements.

**Use Cases:**

- Log-In
- Log-Out
- Managing own Account
- Administrate AAS content
- Administrate accounts
- Find asset

**Functional Requirements:**

- GUI Components
- Identity & Access Management
- Error Display
- AAS content data management
- Search functionalities

**Non-Functional Requirements:**

- Usability
- Reliability

**Other Product Characteristics:**

- System Environment

We would like to know if all these details are in order and if you would like any other specific use cases and requirements. These are the use cases and requirements that our product manager put together in collaboration with the documents you provided.
We also wanted to get your opinion on the Product Data section. The question here is whether the following content belongs in the CRS. 

**Product Data:**

- MongoDB

We would also like to know if the derivation of the specific target group or just the indication without detailed justification should be included.
Thank you for your help and we look forward to your response!

Kind Regards,
Luka Pavic in the name of Team 2

[TINF21C_CRS_Team_2_0v1.docx](https://github.com/JoTec2002/TINF21C_AAS_Management/files/9844325/TINF21C_CRS_Team_2_0v1.docx)

**Comment by mrentsch65** [comment]
### I would see the following as relevant:

**Use Cases**:
Log-In
Log-Out
Managing own Account
Administrate accounts
Administrate AAS content
Find Asset
Display Asset
Edit Asset (optional)

**Functional Requirements**:
Identity & Access Management
AAS content data management
Search functionalities
REST-API support (https://app.swaggerhub.com/apis/BaSyx/basyx_asset_administration_shell_repository_http_rest_api/v1)
Error Display

**Non-Functional Requirements**:
Usability
Reliability

**Other Product Characteristics:**
System Environment

**Product Data:**
MongoDB

**Comment by LukaDPavic** [comment]
Dear Customer (@mrentsch65),

**Thank you very much for your detailed feedback!**

One question remained open on the topic of "target group". Which contents would you like to have listed or are you of the opinion that this point is not relevant?

Thank you in advance!

Kind Regards,
Luka Pavic in the name of Team 2

**Comment by mrentsch65** [comment]
If you mean with "target group" the intended user groups of the AAS Management: Yes, it is important to identify and describe them.
