### ISSUE TITLE
Problems Reading AASX Files

### ISSUE THREAD

**Issue by JoTec2002** [JoTec2002/TINF21C_AAS_Management#17]
Dear @mrentsch65,

when we try to read the AASX-files we're unable to decrypt the content.
The File downloaded from https://v3.admin-shell-io.com/ is readable by the aasx package explorer (https://github.com/admin-shell-io/aasx-package-explorer/) so the file itself is not the Problem.
If we open the file we get somethings in the line of "PK   +O‡UH`˜         aasx/aasx-originóÌ+IÍ+ÉÌÏKÌÉ©THÍ-(©Ô PK   +O‡Uê". 
The official Documentation https://www.plattform-i40.de/IP/Redaktion/DE/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V2.pdf?__blob=publicationFile&v=6 isn't a help in this regard. Could you help us with information how to decrypt the content of the AASX-files.

**Comment by mrentsch65** [comment]
An AASX-File follows the [Open Package Convention](https://en.wikipedia.org/wiki/Open_Packaging_Conventions). You can simply [unzip](https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc) it.
