### ISSUE TITLE
SubmodelsID and IdShortPath

### ISSUE THREAD

**Issue by selvanadwiayunda** [JoTec2002/TINF21C_AAS_Management#52]
for the pic and the others, need valid submodelsID and IdShortPath (DeteilsProdukt.js)

**Comment by JoTec2002** [comment]
Recomandation to get all data:
1. Call /shells on page load. display idShort and Store ID(base64Url encoded)

2. On Click on Asset: 
2.1 Call /shells/{IDbase64UrlEncoded}/submodels -> store in array 1
2.2 Iterate Over array 1 by calling /submodels/{key found in array} -> display idShort in Dropdown Style store ID

3. On Click on Dropdown:
3.1 Call /submodels/[submodelId]/submodelelements story in array 2
3.2 Iterate over array 2 and change next action according to modelType
3.2.modelType=Property -> Display idShort:value
3.2.modelType=SubmodelElementCollection -> Display as Dropdown Dropdown content from array key value (repete 3.2 on value content; store/append idShort for possible File Calls).
3.3.modelType=File -> run API Call on /submodels/[submodelId]/submodelelements/{idShortPath}/attachment -> Display picture

**Comment by selvanadwiayunda** [comment]
@JoTec2002 DeteilsProdukt.js id repeated continuously 👎
