### ISSUE TITLE
BC

### ISSUE THREAD

**Issue by selvanadwiayunda** [JoTec2002/TINF21C_AAS_Management#6]
@Mohitibashi 

- [x] Kostenrechnung
- [x] Rentabilitätsrechnung
- [x] Projektplanung als GANTT-Diagramm

Deadline: 30.10.2022

**Comment by Mohitibashi** [comment]
[TINF21C_Team2_BC.docx](https://github.com/JoTec2002/TINF21C_AAS_Management/files/9788559/TINF21C_Team2_BC.docx)

**Comment by Mohitibashi** [comment]
[TINF21C_Team2_BC.docx](https://github.com/JoTec2002/TINF21C_AAS_Management/files/9833071/TINF21C_Team2_BC.docx)
