### ISSUE TITLE
Bug in submodel-Requests

### ISSUE THREAD

**Issue by paulbrenner2** [JoTec2002/TINF21C_AAS_Management#65]
Request for all submodels fail, e.g.:
`{
  "messages": [
    {
      "code": "NotFound",
      "messageType": "Error",
      "text": "Submodel with id VmpKMFUxUXlSWGROU0dSc1UwWktWbGx0ZUhkalJsbDNWbXQwYVUxWGVEQlViR2hMWVRGYWRHUkVWbFZOVjJoVVZrWlZlR1JIVmtsVGJIQk9UVzVOZUZkc1kzaFRNVnBHVDFWV1ZHRjZiRmhWYlRFelRXeFpkMkZJWkZkaVZrWXpWR3hTWVZaSFNsZGpSa0poVmpOU1IxUldXbE5XTVdSVlZXczFVMVpGV2pSV2FrWlRWR2M not found.",
      "timestamp": "20.04.2023 14:49:20"
    }
  ],
  "success": false
}`

No authentication problem, since not a "forbidden" error.

**Comment by JoTec2002** [comment]
32209480338e0bb5c8147192576ba59a19170298
