### ISSUE TITLE
Request Customer Feedback for frontend

### ISSUE THREAD

**Issue by JoTec2002** [JoTec2002/TINF21C_AAS_Management#81]
@mrentsch65 please review this project.

**Comment by mrentsch65** [comment]
1) Die Header-Bar bietet noch deutliches Optimierungspotential
2) Es wäre von der Usability her besser, wenn zumindest das Nameplate-Submodelle per Default aufgeklappt wäre
3) Bitte die Daten entsprechend der hierarchischen Struktur gruppieren
4) Der Login-Mechanismus verhält sich inkonsistent

![image](https://user-images.githubusercontent.com/50681355/236607902-75c4604e-b420-40bf-9d6e-d9e45a0db97f.png)

**Comment by mrentsch65** [comment]
Die AAS-Id ist in der Datei enthalten und sollte von dort ausgelesen werden:
![image](https://user-images.githubusercontent.com/50681355/236608179-1ddcfdd5-c21c-44ad-8566-3d27b52fbbd4.png)

**Comment by mrentsch65** [comment]
Hier wäre es besser, den Workflow-Zustandswechsel durch umschalten der Buttons entsprechend anzuzeigen. Bspw. könnte nach erfolgreichem hochladen aus dem "Submit"  ein "Asset anzeigen" - Button werden:

![image](https://user-images.githubusercontent.com/50681355/236608259-32eab238-8eda-4fad-8046-7c9a72bfd15d.png)

**Comment by mrentsch65** [comment]
Die Liste sollte scrollbar sein, sonst verliert man den Zusammenhang zum angezeigtem Inhalt:
![image](https://user-images.githubusercontent.com/50681355/236608448-41f8372f-d677-46cd-b655-8bf58f75f5aa.png)

**Comment by mrentsch65** [comment]
Versuchen Sie mal diese Datei zu laden (in der [Nextcloud](https://nextcloud.dhbw-stuttgart.de/index.php/apps/files/?dir=/SWE1/TINF21C&fileid=22978785) abgelegt) :
![image](https://user-images.githubusercontent.com/50681355/236608747-10c8681f-e144-47ad-9d31-46795fd6f1a7.png)

**Comment by mrentsch65** [comment]
Fehlermeldungen sollten farblich abgehoben angezeigt werden. Und sind das wirklich Fehler oder nur Leerstellen? Der AASX-Explorer zeigt keine Fehler an.

![image](https://user-images.githubusercontent.com/50681355/236608982-7b0d9f16-06e4-481d-bf75-883f71a7e996.png)

Die Datei ist in der [Nextcloud](https://nextcloud.dhbw-stuttgart.de/index.php/apps/files/?dir=/SWE1/TINF21C&fileid=22978785) abgelegt.

**Comment by mrentsch65** [comment]
Bitte "**Loding Details**" zu "**Loading Details**" korrigieren.

**Comment by mrentsch65** [comment]
Bei einigen Assets werden keine Submodelle angezeigt, obwohl definitiv welche vorhanden sind:
![image](https://user-images.githubusercontent.com/50681355/236609245-69b97cc5-8962-4d2f-8e1d-ccc072f4cd68.png)
