### ISSUE TITLE
Bitte "**Loding Details**" zu "**Loading Details**" korrigieren.

### ISSUE THREAD

**Issue by JoTec2002** [JoTec2002/TINF21C_AAS_Management#92]
Bitte "**Loding Details**" zu "**Loading Details**" korrigieren.

_Originally posted by @mrentsch65 in https://github.com/JoTec2002/TINF21C_AAS_Management/issues/81#issuecomment-1537075021_

**Comment by paulbrenner2** [comment]
Fixed in Pull Request #102
