### ISSUE TITLE
Test AASX Upload with specific AAS

### ISSUE THREAD

**Issue by JoTec2002** [JoTec2002/TINF21C_AAS_Management#94]
Versuchen Sie mal diese Datei zu laden (in der [Nextcloud](https://nextcloud.dhbw-stuttgart.de/index.php/apps/files/?dir=/SWE1/TINF21C&fileid=22978785) abgelegt) :
![image](https://user-images.githubusercontent.com/50681355/236608747-10c8681f-e144-47ad-9d31-46795fd6f1a7.png)

_Originally posted by @mrentsch65 in https://github.com/JoTec2002/TINF21C_AAS_Management/issues/81#issuecomment-1537074091_

**Comment by selvanadwiayunda** [comment]
This AASX file could not be uploaded to the server.

**Comment by JoTec2002** [comment]
![image](https://user-images.githubusercontent.com/82174634/237029910-f3d9db3a-6ea1-4160-9025-07d9102953f9.png)

File is to large for upload adding upload limit in #106

**Comment by paulbrenner2** [comment]
Fixed in #106.
Upload of this file is not possible (IDTA limit). Error message will be displayed.
