### ISSUE TITLE
Restyle Upload

### ISSUE THREAD

**Issue by JoTec2002** [JoTec2002/TINF21C_AAS_Management#96]
Hier wäre es besser, den Workflow-Zustandswechsel durch umschalten der Buttons entsprechend anzuzeigen. Bspw. könnte nach erfolgreichem hochladen aus dem "Submit"  ein "Asset anzeigen" - Button werden:

![image](https://user-images.githubusercontent.com/50681355/236608259-32eab238-8eda-4fad-8046-7c9a72bfd15d.png)

_Originally posted by @mrentsch65 in https://github.com/JoTec2002/TINF21C_AAS_Management/issues/81#issuecomment-1537070729_

**Comment by JoTec2002** [comment]
Add react state for succesfull Upload.

Change Button, if upload successfull.

**Comment by paulbrenner2** [comment]
Done in #108
